### ISSUE TITLE
bugfix: 特性开关功能，删除业务灰度白名单不生效

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#1835]
**Version / Branch / tag**

3.7.1

**出了什么问题？(What Happened?)**

特性开关功能，删除业务灰度白名单不生效

原始配置:
```
job
  features:
    gseV2:
      enabled: true
      strategy:
        id: "ResourceScopeWhiteListToggleStrategy"
        params:
          resourceScopeList: "biz:2,biz:41"
```
修改为如下配置，去掉biz:41这个灰度业务
```
job
  features:
    gseV2:
      enabled: true
      strategy:
        id: "ResourceScopeWhiteListToggleStrategy"
        params:
          resourceScopeList: "biz:2"
```

执行/actuator/busrefresh 刷新配置之后，业务ID=41这个业务仍然是使用了GSEV2版本，与预期不符

**如何复现？(How to reproduce?)**

多次更新特性开关配置，新的配置不生效

**预期结果(What you expect?)**
