### ISSUE TITLE
fix: 容器化版本 Job 更改 values.yml 中的特性开关配置不生效

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#2173]
**Version / Branch / tag**

3.7.x

**出了什么问题？(What Happened?)**
values.yml 原始配置：
```
job:
  features:
    gseV2:
      enabled: true
```
修改配置，增加 gseFileProtocolBeforeV2 的特性
```
job:
  features:
    gseV2:
      enabled: true
    gseFileProtocolBeforeV2:
      enabled: true
```

执行 helm upgrade 之后，发现 values 对应的 ConfigMap 并没有生效。找到对应的 ConfigMap 的定义，代码如下：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-common-refreshable
  namespace: {{ .Release.Namespace }}
  labels:
    spring.cloud.kubernetes.config: "true"
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-common-refreshable"
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    spring.cloud.kubernetes.configmap.apps: "job-analysis,job-backup,job-crontab,job-execute,job-file-gateway,job-gateway,job-logsvr,job-manage"
data:
  application.yaml: |-
    job:
      features:
        fileManage:
          enabled: {{ .Values.job.features.fileManage.enabled }}
        bkBizIdCompatible:
          enabled: {{ .Values.job.features.bkBizIdCompatible.enabled }}
        gseV2:
          enabled: {{ .Values.job.features.gseV2.enabled }}
          {{- if .Values.job.features.gseV2.strategy }}
          strategy:
            id: {{ .Values.job.features.gseV2.strategy.id }}
            {{- if .Values.job.features.gseV2.strategy.params }}
            params: {{- include "common.tplvalues.render" ( dict "value" .Values.job.features.gseV2.strategy.params "context" $ ) | nindent 14 }}
            {{- end }}
          {{- end }}
```
里边特性开关配置这里是写死的，没有 `gseFileProtocolBeforeV2` 这个特性，所以通过 helm upgrade 生成的 ConfigMap 并不会改变

**如何复现？(How to reproduce?)**

必现

**预期结果(What you expect?)**

执行 helm upgrade 之后，发现 values 对应的 ConfigMap 生效
